insert into cities (city_id, city_name) values (1, 'Saint-Denis');
insert into cities (city_id, city_name) values (2, 'Takahagi');
insert into cities (city_id, city_name) values (3, 'Zátor');
insert into cities (city_id, city_name) values (4, 'Geser');
insert into cities (city_id, city_name) values (5, 'Ginir');
insert into cities (city_id, city_name) values (6, 'Rosmalen');
insert into cities (city_id, city_name) values (7, 'Diez de Octubre');
insert into cities (city_id, city_name) values (8, 'Vannes');
insert into cities (city_id, city_name) values (9, 'Lewisporte');
insert into cities (city_id, city_name) values (10, 'Balingcanaway');
insert into cities (city_id, city_name) values (11, 'Caoxi');
insert into cities (city_id, city_name) values (12, 'Koumra');
insert into cities (city_id, city_name) values (13, 'Mata-Utu');
insert into cities (city_id, city_name) values (14, 'Gengcheng');
insert into cities (city_id, city_name) values (15, 'Fakaifou Village');
insert into cities (city_id, city_name) values (16, 'San Isidro');
insert into cities (city_id, city_name) values (17, 'Vanadzor');
insert into cities (city_id, city_name) values (18, 'Klobuky');
insert into cities (city_id, city_name) values (19, 'Cholet');
insert into cities (city_id, city_name) values (20, 'Bunder');
